import { createFileRoute } from '@tanstack/react-router'
import { LegalPage, legalHead } from '../components/LegalPage'

export const Route = createFileRoute('/privacy')({ head: () => legalHead('Privacy Notice', 'How My Locs Thrive collects, uses, stores and protects information submitted through this website.', 'privacy'), component: PrivacyPage })

function PrivacyPage() {
  return <LegalPage title="Privacy Notice" intro="This notice explains the limited personal information My Locs Thrive collects and the choices available to you." sections={[
    { heading: 'Information collected', content: <><p>When you request the starter guide or ask to hear about Learning Circles, the site collects your email address and the signup source. Requesting the guide also registers you for occasional Notes From the Journey. The contact form collects your name, email address and message. A hidden spam-prevention field may also be processed.</p><p>The hosting provider may process basic technical request information such as an IP address, browser type, requested page and time of access for security, delivery and aggregated site measurement.</p></> },
    { heading: 'Why it is collected', content: <ul><li>To deliver the guide or information you requested.</li><li>To send occasional educational emails when you have joined the newsletter.</li><li>To respond to contact messages.</li><li>To prevent spam, maintain security and understand basic site performance.</li></ul> },
    { heading: 'Providers and processing', content: <p>Netlify hosts this website and processes form submissions through Netlify Forms. Form records and technical request data may therefore be processed on Netlify’s infrastructure. No third-party advertising trackers, behavioural advertising pixels or cross-site marketing cookies are intentionally used in this version of the site.</p> },
    { heading: 'Retention', content: <p>Newsletter details are kept while you remain subscribed and for a limited period afterwards where needed to respect an unsubscribe request. Guide and Learning Circle requests may be retained for up to 24 months for delivery and administration. Contact messages may be retained for up to 24 months unless a longer period is reasonably needed to resolve the enquiry or meet a legal obligation. Spam and security records may be retained for a shorter or longer period according to Netlify’s service practices.</p> },
    { heading: 'International transfers', content: <p>Netlify is a United States-based provider operating global infrastructure. Information may be processed outside your country. Where data-protection law requires safeguards for an international transfer, the relevant provider is responsible for applying its contractual and legal safeguards.</p> },
    { heading: 'Your choices and rights', content: <p>You can unsubscribe from newsletter emails at any time using the link in an email. You may also ask to access, correct or delete personal information connected with your email address, or object to further use. Rights vary by location and may be subject to lawful exceptions.</p> },
    { heading: 'Adults only', content: <p>Newsletter and guide registration is intended for adults aged 18 and over. My Locs Thrive does not knowingly solicit personal information directly from children. If you believe a child has submitted information, please use the contact page to request deletion.</p> },
    { heading: 'Privacy contact', content: <p>Use the <a href="/contact">contact page</a> and select “Privacy request” in your message. Include the email address connected with your request so the relevant record can be located. Do not send sensitive medical information.</p> },
  ]} />
}
